version: '3.8'
services:
  db:
    image: mysql:${MYSQL_VERSION}
    ports:
      - ${DATABASE_PORT}:${DATABASE_PORT}
    environment:
      MYSQL_USER: ${DATABASE_USER:-alfred}
      MYSQL_PASSWORD: ${DATABASE_PASSWORD:-secret}
      MYSQL_DATABASE: ${DATABASE_NAME:-site}
      MYSQL_ROOT_PASSWORD: ${DATABASE_ROOT_PASSWORD:-rootsecret}
      TZ: 'Europe/Bucharest'
    healthcheck:
      test: 'exit 0'
    restart: always
    volumes:
      - db:/var/lib/mysql
      # - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
volumes:
  db: